export const SKILLS_LOADING = "SKILLS_LOADING";
export const SKILLS_FAILED = "SKILLS_FAILED";
export const SKILLS_LOADED = "SKILLS_LOADED";

export const USER_LOADING = "USER_LOADING";
export const USER_FAILED = "USER_FAILED";
export const USER_LOADED = "USER_LOADED";

export const CONTACT_LOADING = "CONTACT_LOADING";
export const CONTACT_FAILED = "CONTACT_FAILED";
export const CONTACT_LOADED = "CONTACT_LOADED";

export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const PROJECTS_FAILED = "PROJECTS_FAILED";
export const PROJECTS_LOADED = "PROJECTS_LOADED";

export const BOOKMARKS_LOADING = "BOOKMARKS_LOADING";
export const BOOKMARKS_FAILED = "BOOKMARKS_FAILED";
export const BOOKMARKS_LOADED = "BOOKMARKS_LOADED";

export const EMPLOYMENTS_LOADING = "EMPLOYMENTS_LOADING";
export const EMPLOYMENTS_FAILED = "EMPLOYMENTS_FAILED";
export const EMPLOYMENTS_LOADED = "EMPLOYMENTS_LOADED";

export const EDUCATIONS_LOADING = "EDUCATIONS_LOADING";
export const EDUCATIONS_FAILED = "EDUCATIONS_FAILED";
export const EDUCATIONS_LOADED = "EDUCATIONS_LOADED";

export const REVIEWS_LOADING = "REVIEWS_LOADING";
export const REVIEWS_FAILED = "REVIEWS_FAILED";
export const REVIEWS_LOADED = "REVIEWS_LOADED";

export const REQUESTS_LOADING = "REQUESTS_LOADING";
export const REQUESTS_FAILED = "REQUESTS_FAILED";
export const REQUESTS_LOADED = "REQUESTS_LOADED";

